#============== kafka ===================
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4
#每次批量发送消息的数量
    producer:
      batch-size: 1000
# 指定默认消费者group id
    consumer:
      group-id: myGroup
# 指定默认topic id
    template:
      default-topic: topic-1
logging:
  level:
    root: info